In [1]:
import fredapi as fa
from datetime import date
import pandas as pd

fred = fa.Fred('4fb0ce271d0f66f4b5b3904b4aaf1dd0')

#fr = FRB.fred.Fred(api_key="4fb0ce271d0f66f4b5b3904b4aaf1dd0",response_type='dict')

In [3]:
import yfinance as yf


fact = pd.DataFrame()
fact['Value'] = yf.download(["VLUE"], start = '2010-01-04', progress=False)["Close"]
fact['Quality'] = yf.download(["QUAL"], start = '2010-01-04', progress=False)["Close"]
fact['Size'] = yf.download(["SIZE"], start = '2010-01-04', progress=False)["Close"]
fact['Default'] = yf.download(["FIBR"], start = '2010-01-04', progress=False)["Close"]
fact['Real Yield'] = fred.get_series('DFII10', observation_start = '2010-01-04', end = date.today())
fact['Yield Curve'] = fred.get_series('T10Y2Y', observation_start = '2010-01-04', end = date.today())

In [2]:

#fact = fact.dropna()


factor_df = pd.read_csv("regular_factors_and_rates.csv", index_col = "Date")

factor_df['Inflation'] = fa.

,DEFAULT,QUALITY,MOMENTUM,BOOK_TO_PRICE,SIZE,CASH_TO_ASSETS,Real Yield,Yield Curve
Date,,,,,,,,
1/4/2010,0.0230,-0.0233,0.0059,0.0034,0.0057,-0.0033,1.47,2.76
1/5/2010,0.0259,-0.0209,0.0064,0.0053,-0.0067,0.0018,1.43,2.76
1/6/2010,0.0035,-0.0058,-0.0004,0.0015,-0.0034,-0.0021,1.48,2.84
1/7/2010,0.0261,-0.0092,-0.0085,0.0084,0.0088,0.0019,1.44,2.82
1/8/2010,0.0013,-0.0018,0.0020,0.0078,0.0075,-0.0025,1.41,2.87
...,...,...,...,...,...,...,...,...
2/11/2022,-0.0089,-0.0053,0.0073,0.0190,0.0022,-0.0210,-0.51,0.42
2/14/2022,-0.0091,0.0065,-0.0007,0.0009,-0.0030,-0.0029,-0.50,0.40
2/15/2022,0.0306,-0.0233,-0.0092,-0.0173,0.0107,0.0344,-0.43,0.47
2/16/2022,-0.0055,-0.0026,0.0065,0.0078,0.0033,-0.0161,-0.43,0.51
2/17/2022,-0.0180,0.0026,0.0103,0.0200,0.0050,-0.0351,-0.46,0.48

In [3]:
from Sector_Exposure import Rate_Exposures

#yf.download(["VFVA"], start = '2010-01-04', progress=False)["Close"]

#factor_df = pd.read_excel("factors_and_scores.xlsx")
#factor_df['Real Yield'] = fred.get_series('DFII10', observation_start = '2010-01-04', end = date.today())
#factor_df['Yield Curve'] = fred.get_series('T10Y2Y', observation_start = '2010-01-04', end = date.today())

#factor_df = factor_df.drop(columns = ['ry_scores', 'yc_scores'])

ok = Rate_Exposures(factor_df, 252, 30, ['Real Yield', 'Yield Curve'])

1

In [7]:



ok.mean_returns

        DEFAULT   QUALITY  MOMENTUM  BOOK_TO_PRICE    SIZE  CASH_TO_ASSETS
-6 -5 -0.091200  0.035100   0.07930        -0.0544 -0.0563         0.01890
   -4 -0.107200  0.088100   0.02660        -0.0241 -0.0447         0.02730
    0 -0.009200  0.102800   0.04220        -0.1383 -0.0262         0.15250
    2  0.001400  0.007800  -0.00310        -0.0627 -0.0475         0.06210
    5 -0.010600  0.118500   0.03170        -0.1334 -0.0278         0.12310
...         ...       ...       ...            ...     ...             ...
 5  4 -0.019900  0.005150   0.00960         0.0165  0.0335         0.03090
    5  0.009300 -0.000600   0.01815        -0.0020  0.0244         0.04945
 6  3 -0.028333  0.003683   0.01145         0.0170  0.0278         0.00805
    4 -0.029800  0.009500   0.00210         0.0123  0.0275         0.02290
    5  0.011200 -0.006300   0.03700        -0.0121  0.0254         0.03470

[111 rows x 6 columns]